language: c
sudo: false
addons:
  apt:
matrix:
    include:
        - name: Linux (gcc-8)
          os: linux
          dist: xenial
          compiler: gcc-8
          addons:
             apt:
               sources:
                 - ubuntu-toolchain-r-test
               packages: g++-8
        - name: Linux (clang)
          os: linux
          dist: xenial
          compiler: clang
        - name: macOS (xcode)
          os: osx
        - name: macOS (xcode 10.1)
          os: osx
          image: xcode10.1
        - name: Linux (scan-build)
          os: linux
          dist: xenial
          env:
              - CC=/usr/local/clang/libexec/ccc-analyzer
              - CXX=/usr/local/clang/libexec/c++-analyzer
              - EXTRA="scan-build"
before_install:
  - $CC --version
  - cmake --version
before_script:
  - ${EXTRA} cmake .
script:
  - ${EXTRA} make
  - make test
